Azure-Samples/azure-search-openai-demo

README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update README.md to highlight important note

---

azure.yaml

Adding metadata to measure provisions/deploys of this app template

Adding metadata to measure telemetry

---

scripts/prepdocs.py

Remove unsupported characters from Azure Search section id.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
Run preprocessing script for document which contains some unsupported characters (i.e. '+'). Before preprocessing script would fails, no these characters will be replaced with '_' in the section id.
```

Remove unsupported characters from Azure Search section id

---

README.md

This will help clarify that env flag is required when sharing environments.

Add -e flag

---

scripts/prepdocs.sh

quick PR.  the argument is missing `id`

Update `tenantid` argument

---

infra/main.parameters.json
scripts/prepdocs.sh

* ...
```
[ ] Yes
[X ] No
```
```
[ x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
main.parameter.json was missing two parameters for the AZURE_OPENAI_GPT_DEPLOYMENT and AZURE_OPENAI_CHATGPT_DEPLOYMENT so no deployment with models named other than "chat" and "davinci" would succeed. Adding those two parameters passed the model names through to deployment.

fixed main.parameters.json to take openai models

---

infra/main.parameters.json

Revert the changes in #176 to temporarily fix #120

Revert parameterised GPT resources

---

app/backend/approaches/readretrieveread.py

The lookup tool needs to parse the input to find the employee name. This parsed name should not be discarded, instead it should be used to lookup the employee
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Try the following question using the read, retrieve, read approach. Employee2's information should be retrieved
What is Employee2's health plan?

Update read, retrieve, read approach

---

app/backend/app.py
app/backend/approaches/approach.py
app/backend/approaches/chatreadretrieveread.py
app/backend/approaches/readdecomposeask.py
app/backend/approaches/readretrieveread.py
app/backend/approaches/retrievethenread.py
app/backend/langchainadapters.py
app/backend/lookuptool.py

These were identified by adding the following to `.vscode/settings.json`
```javascript
"python.analysis.diagnosticMode": "workspace",
"python.analysis.autoSearchPaths": true,
"python.analysis.typeCheckingMode": "basic"
```

Fix some of the type annotations

---

README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Updated available location info of Open AI added France Central, West Europe and removed South Central US

---

app/backend/approaches/readretrieveread.py

* Just removed the duplicated imports.
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/approaches/readretrieveread.py#L5-L9
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
NA
NA
Before:
```sh
$ flake8 --select=F811           
./app/backend/approaches/readretrieveread.py:9:1: F811 redefinition of unused 'AzureOpenAI' from line 5
```
After:
```sh
$ flake8 --select=F811
```

Remove duplicated import

---

app/backend/requirements.txt
notebooks/requirements.txt
scripts/requirements.txt

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update identity-sdk-client to latest GA

---

README.md

Super small fix to match formatting of "azd deploy" throughout the README. In the last line, it was wrapped in single quotes instead of backticks, making it inconsistent with the rest of the README. 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
Nothing to test, just read the last line of the README.
* No other changes have been made

Update README.md line to match previous formatting

---

app/backend/approaches/chatreadretrieveread.py
app/backend/approaches/readretrieveread.py
app/backend/approaches/retrievethenread.py

**Opinionated change, feel free to disregard.**
Convert comments to docstrings to make the code more pythonic 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```

Turn class comments into class docstrings

---

README.md

Fixed markdown violations for better readability in accordance with markdown linter/best-practices.
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[X ] Documentation content changes
```
N/A
N/A
* Markdown formatting.
*

Fixed markdown violations.

---

app/start.ps1
app/start.sh

This PR updates the start commands to use "flask run" instead of calling app.py, as that's considered the better practice. It also makes it easier to specify the port, which I think is very important, since it's very common to have port collisions (especially with 5000 on Macs).
I also added arguments to enable the debugger and hot reloading, for easier local development.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Run `./start.sh`, be able to use website
* Run `pwsh start.ps1`, be able to use website
* Make a change to app.py and see it reload

Use flask run command

---

app/frontend/package-lock.json
app/frontend/package.json

* Bump frontend dependencies, to solve security issues and upgrade to latest available versions.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
```
```
cd app
start.ps1 or start.sh
```
* App builds and load successfully

Bump frontend dependencies

---

app/backend/app.py
app/backend/approaches/chatreadretrieveread.py
app/backend/requirements.txt

Upgrade Sample to use ChatCompletion API of gpt-35-turbo model
* ...
```
[x ] Yes
[ ] No
```
1. Update openAI lib to use chatcompletion api
2. Update api version to latest
3. Contract changes for chatcompletion scenario
4. use openAI tiktok lib to validate token
```
[ ] Bugfix
[x ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Upgrade sample to use ChatCompletion API

---

app/backend/approaches/chatreadretrieveread.py

Update thought process tab to include system prompt and conversations from chat/completion api
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

[UX] Update 'thought process' to include conversations

---

README.md

This PR updates the readme with some FAQs and rewording based on recent support issues.
If we're worried about the FAQs adding too much length to the readme, we could use HTML details/summary elements (GitHub supports!) so that only the questions are visible by default.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Update readme FAQs

---

CONTRIBUTING.md
app/backend/core/messagebuilder.py
app/backend/core/modelhelper.py
pyproject.toml
requirements-dev.txt
tests/test_messagebuilder.py
tests/test_modelhelper.py
tests/test_prepdocs.py

This PR adds tests for the core/ folder and addresses a potential issue.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Follow new instructions in CONTRIBUTING.md :)

Add more tests for core/ folder

---

.github/workflows/azure-dev-validation.yaml
infra/core/host/appservice.bicep

This PR adds a workflow that ensures the Bicep is valid, using az bicep build.
(It does not use the template-analyzer due to issues discovered in PR #444 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
Create PR and wait for action to succeed.

Add simple validation

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

There's now an azd feature for dev containers, which will automatically download the appropriate azd for your architecture (arm/amd) so platform emulation is no longer needed.
This PR updates the dev container to use that feature.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Open in Dev Container in VS Code
* Confirm azd works
* Confirm local server works

Using azd feature

---

.github/workflows/python-test.yaml
app/backend/core/modelhelper.py

Apparently some developers are using Python 3.8 to run this code, so we should run tests on 3.8  and 3.9 as well. This PR adds them to the test matrix and fixes a typing related issue.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Wait for tests to pass! :)

Add 3.8 and 3.9 to test to matrix, fix type bug

---

scripts/prepdocs.py

This PR replaces "import *" with explicit imports. Generally, "import *" should be avoided when possible, and I'm not sure if it's contributing to bugginess for some users (#450).
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Get the code
* Run azd up
* See prepdocs successfully complete

Update imports to explicit named imports for prepdocs

---

README.md
infra/main.bicep

Now that this template includes ada, there is a smaller list of compatible regions:
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#embeddings-models-1
This PR updates the readme and Bicep.
If someone previously deployed to a non ada region, theyll get an error, but I think theyd get it anyway due to ada not being supported.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
*  Run azd up, get less regions in picker, deploy successfully

Adjust regions

---

README.md

Adding answer to question I get sometimes. (Just came up in an issue)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Update README.md with FAQ comparing to other repo

---

scripts/prepdocs.py

* charcters -> characters
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix typo in prepdocs.py

---

README.md

* Typo "Azure Open AI"→"Azure OpenAI"
https://github.com/Azure-Samples/azure-search-openai-demo/edit/main/README.md 
#PingMSFTDocs
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Typo "Azure Open AI"→"Azure OpenAI"

---

README.md

Location list was outdated and location is now constrained with allowed decorator, so I reworded the readme accordingly.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Update README.md location list

---

README.md

This PR adds an FAQ about using gpt-4, as it's coming up a lot. This should be merged after #550 since that fixes some related code.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Update README.md FAQ re gpt-4

---

README.md

This PR adds a table of contents to the top level `readme` allowing the user to better navigate the documentation.
Will happily move it if you think it fits in a better spot in the readme! :)
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Adding table of contents to main readme

---

.github/workflows/azure-dev-validation.yaml

Make SARIF uploads optional but automatic for the main repo

---

README.md

Just adds an FAQ for a good question that was just asked.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Update README.md with chat/ask question

---

README.md

Just slight wording tweak based on user study.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Update README.md deploying section

---

infra/core/storage/storage-account.bicep

Fixes #580 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```

Explicitly set https required

---

README.md

Trying to clarify the various requirements more clearly by using bullet points, and also added a suggestion of the RBAC role which is new but seems to work (at least at subscription level).
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Update README.md with account reqs

---

infra/main.bicep
infra/main.parameters.json

Some users may have Standard_ZRS (especially if they deployed before we changed default to Standard_LRS). Adding to main.parameters.json so it can be easily configured in the azd environment. Mostly helps me as I constantly switch envs :)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
for env with ZRS:
* azd env set AZURE_STORAGE_SKU Standard_ZRS
* azd up
* works!
for normal env, azd up

Add parameter for configuring storage sku

---

app/frontend/src/pages/chat/Chat.tsx
app/frontend/src/pages/oneshot/OneShot.tsx

I've had two questions today about "Retrieve this many documents from search:" where devs were worried it wouldn't be searching all the documents. I've attempted a reword.
(Also, "documents" seems misused here, since all chunks could come from same PDF, right?)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* run local server, see label

Reword top label

---

.github/workflows/python-test.yaml
.pre-commit-config.yaml
app/backend/app.py
app/backend/approaches/chatreadretrieveread.py
app/backend/approaches/readdecomposeask.py
app/backend/approaches/readretrieveread.py
app/backend/approaches/retrievethenread.py
app/backend/core/messagebuilder.py
app/backend/core/modelhelper.py
app/backend/langchainadapters.py
app/backend/lookuptool.py
app/backend/text.py
locustfile.py
package-lock.json
pyproject.toml
scripts/prepdocs.py
tests/test_app.py
tests/test_prepdocs.py

This PR runs black, the most popular Python PEP8-compliant formatter, on all files, and adds it to the pre-commit and CI.
This may be a controversial PR as it touches a lot of files. It would be great if we could have all our code consistently formatted, but since we didn't have formatting enforced from the beginning, adding formatting now causes a lot of changed lines. The largest changes are in prepdocs.py - I'd been running black manually on the other files when I made changes, so they were mostly compliant already.
The drawbacks of this change: 
* Any open PRs will likely have some/more merge conflicts. (But they they can run black on their own changes, yay!)
* Harder to git blame and see actual history of a line of code. There is a way to tell git to ignore this commit history for …

Run black on all Python files

---

README.md

This adds info about minimum permission level and how to deploy to an RG with that RG-level permission. Related to #4 (but doesn't fix entirely).
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Readme on deploying to existing RG

---

README.md

I want to link people directly to particular FAQs. I think GitHub supports manually specifying the anchor tabs like this, but we'll find out soon. If it doesn't, I may end up making small headlines for each one.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Visit FAQ with anchor in URL

Adding anchors to FAQs

---

README.md

This PR adds a comparison table to help people distinguish between the two similar samples.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Comparison table

---

app/frontend/src/components/Answer/Answer.tsx
app/frontend/src/components/Answer/AnswerParser.tsx
app/frontend/src/pages/chat/Chat.tsx
app/frontend/src/pages/oneshot/OneShot.tsx

Allow the streamed output to become visible at a smoother cadence.  
Comparing the left (current streaming) and the right (smooth streaming) a few things are different:
For the first call the response packets arrive at relatively the same rate but ReAct is buffering and displaying them in chunks on the left and displaying them at a fixed rate on the right. Ideally, we want streaming to provide the response at a fixed rate that is faster than typical reading speed, but no faster.  (Zooming into the gif can help see the differences.)
This change includes a fix for streaming responses scrolling past the end of the screen, and another to prevent partial citation text from appearing in the answer and then 'flashing' into the correct format for citations.  
(This is a cherry-picked + squashed …

Smooth streaming, fix partial citation, and ensure visibility.

---

README.md

Running the `azd up` command will incur immediate costs even if the command is not fully executed due to a (Ctrl + C) interruption. It can be helpful to other users to warn them about this potential misuse, enabling them to avoid unnecessary spending.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
*  The code was not changed.
* Review the information added in the README.md

Readme cost warning

---

LoginAndAclSetup.md

* Update docs to make setup of access control clearer. Address specific issues encountered in the setup process.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Address documentation feedback for access control

---

app/frontend/src/pages/chat/Chat.tsx

Address streaming response when clearing chat messages #670 
* ...
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Address Issue #670

---

app/backend/approaches/chatreadretrieveread.py
app/backend/core/messagebuilder.py
tests/test_chatapproach.py
tests/test_messagebuilder.py

* ...
* resolve the bug: [Rag sample clasic] Fix or revisit token estimation
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* ...
* Korean and english words are running out of maximum token limit at the same time.

Normalize text in messages to reduce token length

---

app/frontend/package-lock.json
app/frontend/package.json

Attempt to resolve #671. Underlying error appears to be caused by an error in our npm dependencies
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
`azd up` should not result in packaging errors

Update @azure/msal-browser related dependencies

---

app/backend/app.py

Sigh, I left in print() statements from my debugging. The shame!
We could probably lint-check that once we use logging everywhere.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Rm print statements

---

.github/workflows/python-test.yaml

This PR makes the tests run daily. In theory nothing should break between commits given packages are all pinned, but this would have caught our earlier issue with incompatible package updates, so maybe it'll catch something in future.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Wait for midnight UTC, check actions tab

Daily tests

---

.devcontainer/devcontainer.json
.vscode/extensions.json
.vscode/launch.json
app/frontend/package.json
app/frontend/vite.config.ts

I worked with Aaron Powell (another CDA) to make various improvements to our local development experience, particularly in VS Code. These are initial changes we came up with quickly, Aaron is also going to work on launch.json improvements after this is merged.
This PR:
* Adds the recommended extensions to devcontainer as well
* Updates frontend launch.json configuration to use `npm run dev` command
* Removes unneeded launch.json build configuration (not something that needs to be debugged)
* Removes unneeded `npm run watch` (`npm run dev` is sufficient/better)
* Fixes vite config to proxy all the necessary URLs, so that npm run watch works
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local …
```

Improvements to VS Code and Vite debug experience

---

app/backend/approaches/chatreadretrieveread.py

Solution for a issue - https://github.com/Azure-Samples/azure-search-openai-demo/issues/672
```
[ ] Yes
[X ] No
```
```
[ X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Increased maxtoken to avoid malformed JSON in chatreadretrieveread.py

---

app/frontend/package-lock.json
app/frontend/package.json
tests/test_chatapproach.py

* Resolve #671 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```

Add scheduler package

---

README.md

Replace Remote Containers with Dev Containers
Add instructions for using Dev Containers
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
Follow the instructions in the readme.md for using Dev Containers
```
* ...

Update Readme.md - Dev Containers

---

.github/workflows/python-test.yaml

I used the wrong value for the conditional in the runner, so currently tests are never running. I changed it to != and used the correct value.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Check the actions actually run the tests in Ubuntu.

Fix if for tests running conditional

---

README.md

This sample is not currently discoverable in the Azure Samples browser:
https://learn.microsoft.com/en-us/samples/browse/
We'd like all the OpenAI chat sample apps to be indexed there, but that requires adding some YAML to README.md.
Instructions here:
https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main#add-metadata-to-readme
Unfortunately, the YAML will get rendered in the README.md. We've given feedback to the Learn.com that we don't want to have it visible, but for now, we don't see a way to hide it.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature …
```

Add front-matter needed for Sample browser

---

README.md

* Intention is to update existing FAQ with current status based on PR 835
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X ] Documentation content changes
```
*  Review FAQ, question "How can we upload additional PDFs without redeploying everything?"
* Review FAQ, question "How can we upload additional PDFs without redeploying everything?"
n/a

Updated FAQ so that it reflect PR 835

---

infra/main.bicep

All resources are now available in the Australia East region and therefore should make this an allowed deployment region
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe:  Adding more regions to infrastructure Open AI regions to include Australia East
```
cd [repo-name]
npm install
```
execute deployment to Australia East location manually
Confirm all components are deployed successfully.

Including Australia East to allowed regions

---

scripts/prepdocslib/listfilestrategy.py
tests/test_listfilestrategy.py
tests/test_prepdocs.py

Fixes #905 and adds full test coverage for relevant classes (File, LocalListFileStrategy).
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* New tests should pass
* For manual test, make dir in data and run prepdocs, it should index contents.

Test and fix listfilestrategy.py

---

infra/core/ai/cognitiveservices.bicep
infra/core/host/appservice-appsettings.bicep
infra/core/host/appservice.bicep
infra/core/host/appserviceplan.bicep
infra/core/monitor/applicationinsights-dashboard.bicep
infra/core/monitor/applicationinsights.bicep
infra/core/monitor/loganalytics.bicep
infra/core/monitor/monitoring.bicep
infra/core/search/search-services.bicep
infra/core/security/role.bicep
infra/core/storage/storage-account.bicep
infra/main.bicep

Update the infra/core bicep to the latest security improvements

Upgrade infra/core to latest from azd

---

docs/customization.md

Fixing image filenames in doc. I suspect Copilot autocompleted those filenames and I didn't notice. It's not great at guessing filenames.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
I tested by clicking through in VS Code.

Update customization.md with correct image filenames

---

docs/customization.md

This PR is a documentation change to clarify the main ways that a developer can make a particular setting permanent.
Inspired by #883 and other customer questions.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

[Docs] Document how to make setting overrides permanent

---

app/backend/app.py
app/backend/approaches/chatreadretrieveread.py
app/backend/approaches/retrievethenread.py
app/frontend/src/pages/layout/Layout.tsx
docs/customization.md
docs/data_ingestion.md
docs/productionizing.md
infra/core/ai/cognitiveservices.bicep
infra/core/search/search-services.bicep
scripts/manageacl.py
scripts/prepdocs.py

Following up on previous PR #959, this PR renames the remaining instances of Cognitive Search to AI Search.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

[Docs] Rename remaining instances of Cognitive Search to AI Search

---

README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update README.md with link to samples in other languages 

---

infra/core/host/appservice.bicep

I've helped multiple developers debug an issue where their App Service was lacking environment variables, and I've seen it mostly the last few weeks. I'm thinking it's due to the change in https://github.com/Azure-Samples/azure-search-openai-demo/pull/918 that brought in the latest core templates, where appservice.bicep moved app settings into its own module. I'm not sure why exactly that'd break app service, but based on the timing and the issue, it seems likely.
Also, I just helped a developer fix their bug by re-provisioning with the old appservice.bicep.
Thus, I propose going back to the old approach of not putting the settings in a module.
FYI @jongio @wbreza 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Code style update …
```

Fixing app service settings

---

infra/main.bicep

Fixes #990. This PR:
* Makes the dashboard conditional on useApplicationInsights parameter. 
* Removes the "./" in front of the monitoring module location. We don't use "./" in our other core module locations.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* azd up in an environment that doesnt have USE_APPLICATION_INSIGHTS set

[BugFix] Fix "monitoring" related issues in main.bicep

---

app/backend/approaches/chatreadretrieveread.py
app/backend/approaches/retrievethenread.py
app/backend/requirements.in
app/backend/requirements.txt
scripts/prepdocslib/searchmanager.py
scripts/requirements.in
scripts/requirements.txt

This PR updates search to latest version of SDK.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Existing tests still work
* local server works with existing environment
* ./scripts/prepdocs.sh works with existing environment
* azd deploy works with existing environment (pending)

[Backend/Prepdocs] Update to latest version of search SDK

---

.github/workflows/python-test.yaml

Test 3.12 in the CI
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Wait for CI

Update python-test.yaml with 3.12

---

scripts/prepdocs.ps1
scripts/prepdocs.sh

* ...
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Able to run prepdocs without `AZURE_TENANT_ID` defined

Fix prepdocs

---

docs/customization.md

Fixes #1065 by explaining the vision tabs. Let me know if my explanation could be improved!
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```

Explain the vision tabs

---

LoginAndAclSetup.md

Fixes to make optional features work in Dev Container.

Correct pwsh command and location

---

README.md
app/backend/app.py
app/frontend/vite.config.ts
docs/localdev.md
tests/test_app.py

This PR:
* Adds support for local OpenAI-compatible server (tested with llamafile, but conceivably there may be others that could work similarly)
* Fixes local hot reloading (a proxy mapping was missing in the config)
* Adds a document for more details on local development. I plan to add more in future, like section on debugging with VS Code.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Follow steps in local guide, for both using local server and for hot reloading.
* I will add an automated test and update this PR promptly.

Add support for local OpenAI-compatible server, fix local hot reloading, add docs on local dev

---

docs/gpt4v.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Gpt4 + vision -verify access by create deployment

---

README.md

Fixed link in README
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```

Update README.md with correct link

---

app/backend/approaches/approach.py
app/backend/approaches/chatreadretrieveread.py
app/backend/approaches/chatreadretrievereadvision.py
app/backend/approaches/retrievethenread.py
app/backend/approaches/retrievethenreadvision.py
app/backend/core/authentication.py
app/backend/core/modelhelper.py
docs/customization.md
scripts/prepdocslib/filestrategy.py

This pull request primarily focuses on improving the handling of dictionary `get` method calls in the codebase. The changes involve replacing the `or` operator with the default parameter of the `get` method to provide cleaner and more Pythonic code. 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Automated tests

Improve uses of get, fix temperature bug

---

app/backend/approaches/approach.py
app/backend/requirements.in
app/backend/requirements.txt
scripts/prepdocslib/searchmanager.py
scripts/requirements.in
scripts/requirements.txt
tests/test_chatvisionapproach.py

This pull request primarily involves updating the Azure Search Documents SDK from version 11.4.0b11 to 11.6.0b1 and making corresponding changes to the codebase to accommodate the updated SDK. Changes include renaming certain classes and methods, and modifying parameters to match the new SDK's requirements. The changes are spread across the `app/backend/approaches/approach.py`, `app/backend/requirements.in`, `app/backend/requirements.txt`, `scripts/prepdocslib/searchmanager.py`, `scripts/requirements.in`, `scripts/requirements.txt`, and `tests/test_chatvisionapproach.py` files.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
[ …
```

Update Azure AI Search SDK

---

README.md

Thus PR fixes the README to point at new link for doc on login. (Sigh @mattgotteiner I made a big deal of making sure you changed your links and then didn't change this one!)
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
* Preview markdown, click link in it.

Update README.md with new login doc link

---

docs/appservice.md

Fixes Markdown issues, broken images and unclosed tag.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
*  Checked in preview

Fix Markdown typos in App Service Debugging doc

---

scripts/load-balance-aca-setup.sh

This pull request introduces a new shell script `scripts/load-balance-aca-setup.sh`. The script is designed to set up azd environment variables for use with the OpenAI (ACA) load balancer at https://github.com/Azure-Samples/openai-aca-lb. 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Deploy https://github.com/Azure-Samples/openai-aca-lb
* Run this script
* Run app, loadtests

Add setup script for setting up ACA loadbalancer

---

scripts/prepdocs.py

Azure Document Intelligence now supports HTML as well, so this PR adds it.
Fixes #1219
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
*  Tested on my blog:

Add HTML parsing via Azure Document Intelligence

---

app/backend/app.py
app/backend/requirements.in
app/backend/requirements.txt

Implement better LLM tracing with llmetetry OpenAI instrumentation

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This PR updates our template, notably adding sections about whether a change will affect the live tutorial and a contributing checklist. 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Make a new PR :)

Improve PR template to reference tutorial changes and contributing checklist

---

docs/deploy_features.md

Another broken link :( Need a checker. @john0isaac has one.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Documentation content …
```

Update deploy_features.md link

---

infra/main.bicep

If deploying with ACA or APIM custom env var after the load balancer is created, the env var was interfering with the ability for this project to create the resources and ingest the data. 
```
[ ] Yes
[ ] No
```
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
[ ] …
```

Fix provision for load balance custom

---

docs/data_ingestion.md

Fixes broken link
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
``` …

Update data_ingestion.md with correct notebook link

---

app/backend/approaches/approach.py

* Typo "Azure Open AI"→"Azure OpenAI"
* https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/approaches/approach.py
* #PingMSFTDocs
```
[ ] Yes
[x] No
```
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, …
```

Update approach.py (Typo "Azure Open AI"→"Azure OpenAI")

---

docs/gpt4v.md

* Typo "Azure Open AI models"→"Azure OpenAI models"
* https://github.com/azure-samples/azure-search-openai-demo/blob/main/docs/gpt4v.md 
* #PingMSFTDocs
```
[ ] Yes
[x] No
```
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local …
```

Update gpt4v.md (Typo "Azure Open AI models"→"Azure OpenAI models")

---

app/backend/approaches/retrievethenread.py

* Typo "Azure Open AI"→"Azure OpenAI"
* https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/approaches/retrievethenread.py
* #PingMSFTDocs
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update …
```

Update retrievethenread.py (Typo "Azure Open AI"→"Azure OpenAI")

---

infra/core/security/keyvault.bicep

This is a Microsoft best practice for Keyvault deployments
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Documentation content …
```

Force soft delete and purge for keyvault

---

docs/other_samples.md

Just a quick additional row since it's a significant feature.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content …
```

Adding user-upload as a feature in sample comparison

---

docs/localdev.md

Addresses #1476, confusion over OPENAI_HOST value when deploying.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation …
```

Add note about OPENAI_HOST and azd deployment

---

docs/customization.md

Fixed broken links to gptv4.md
```
[ ] Yes
[x ] No
```
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
[ ] Other... Please …
```

Update customization.md - fix broken doc links

---

scripts/roles.sh

Clarify what the roles the user needs to add are.
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] …
```

Add roles descriptions to roles.sh

---

app/frontend/src/components/VectorSettings/VectorSettings.tsx
app/frontend/src/pages/ask/Ask.tsx
app/frontend/src/pages/chat/Chat.tsx

fix #1608 
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
See …

Fix Add Default Key for Retrieval Mode to Persist the Change

---

docs/README.md
docs/deploy_features.md
docs/deploy_private.md

This PR adds sections to the "deploy optional features" to raise discoverability of the private endpoints and load balancing features.
This PR also fixed various markdown issues pointed out by the Markdownlint extension.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
``` …

Additional pointers to docs on private endpoints and load balancing

---

CONTRIBUTING.md
docs/productionizing.md
locustfile.py

This PR adds a HttpUser class to locustfile.py to aid in loadtesting the GPT4-vision use case.
This PR also includes some markdownlint fixes related to READMEs I was updating along the way.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[ ] …
```

Add load testing user class for gpt-4-vision use case

---

samples/chat/README.md
samples/data-ingestion/README.md
samples/document-security/README.md
samples/private-endpoint/README.md

```
[ ] Yes
[ ] No
```
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
See …

Fix samples browser

---

samples/document-security/README.md

```
[ ] Yes
[ ] No
```
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
See …

Fix samples browser - bookmarks

---

infra/main.bicep

Fix #1627 
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```

Fix output variable for global document access

---

docs/deploy_features.md

Updated to latest, stable version. Deployed @ https://app-backend-ixehwdxj5j4oe.azurewebsites.net/
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no …
```

Update GPT-4 version in readme

---

app/backend/app.py
app/backend/approaches/chatreadretrievereadvision.py
tests/snapshots/test_app/test_chat_vision/client1/result.json
tests/snapshots/test_app/test_chat_vision_vectors/client1/result.json
tests/test_chatvisionapproach.py

We shouldn't need to use a vision model for the query rewrite phase. We don't need the vision capability for query rewriting, and the vision models are slower.
You can test the change here:
https://app-backend-xdacsceosefi4.azurewebsites.net/
```
[ ] Yes
[X] No
```
``` …
```

Use chat model for query rewriting

---

app/frontend/src/i18n/tooltips.ts
app/frontend/src/pages/ask/Ask.tsx
app/frontend/src/pages/chat/Chat.tsx

```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
See …

UI developer settings fix

---

app/frontend/src/i18n/tooltips.ts

Quick typo fix.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No - doesnt use vision
```
```
[X] Bugfix
[ ] Feature
[ ] Other... …
```

Fix tooltips typo

---

docs/deploy_private.md

Adds a video link
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No - But I've pinged with with URL to add to VNet doc
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation …
```

Update deploy_private.md with video link

---

.github/workflows/python-test.yaml
app/backend/app.py
infra/main.bicep
infra/main.parameters.json
tests/test_app_config.py

This PR adds support for specifying an API key for Azure OpenAI. We typically do not support key-based access in this repository, but we would like to be able to use this repo with the Azure OpenAI Proxy (a service that advocates use in workshops/hackathons due to the difficulty of getting immediate Azure OpenAI access), which means we need a way of specifying a key.
I also changed the Bicep so that if you are specifying a custom URL for your Azure endpoint, then we do *not* create any Azure OpenAI instance at all. I'm not sure if that's always true, i.e. if developers using the load-balanced OpenAI instances want to skip creating one in this infra. Maybe @andredewes can comment.
Alternatively, I can add an explicit CREATE_AZURE_OPENAI env variable.
When developers merge from main and run …

Add support for specifying an Azure OpenAI Key

---

.github/workflows/python-test.yaml
app/backend/app.py
app/backend/prepdocs.py
app/backend/prepdocslib/embeddings.py
scripts/prepdocs.ps1
scripts/prepdocs.sh
tests/e2e.py
tests/test_app_config.py

This PR adds support for using a key and endpoint for prepdocs.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Documentation …
```

Support use of AzureOpenAI proxy by prepdocs

---

scripts/prepdocs.ps1
scripts/prepdocs.sh

I broke existing environments with previous change due to the way I created the openaikey arg. This constructs it in the way that's compatible with optional args.
```
[ ] Yes
[X] No - I actually tested on an existing env this time. Sorry!
```
```
[ ] Yes
[X] No
```
``` …
```

Fix arg specification

---

app/frontend/src/api/api.ts
app/frontend/src/authConfig.ts
app/frontend/src/components/AnalysisPanel/AnalysisPanel.tsx
app/frontend/src/components/LoginButton/LoginButton.tsx
app/frontend/src/components/QuestionInput/QuestionInput.tsx
app/frontend/src/components/TokenClaimsDisplay/TokenClaimsDisplay.tsx
app/frontend/src/index.tsx
app/frontend/src/layoutWrapper.tsx
app/frontend/src/loginContext.tsx
app/frontend/src/pages/ask/Ask.tsx
app/frontend/src/pages/chat/Chat.tsx

* Issue #1639 was caused by a stale login token not being refreshed after the expiry period
* The login code only fetched the login token once when the page was loaded and did not properly reflect login state changes if the user logged in and out unless the page was refreshed.
* Update the React state management code to use a context to pass login state to all the components that need this to render properly.
```
[ ] Yes
[X] No
```
which includes deployment, settings and usage instructions. If text or …

Fix login state management

---

infra/main.bicep

This PR makes it so you can deploy to private endpoint even if you have the option configured to not provision Azure OpenAI.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no …
```

Make OpenAI deployment optional

---

docs/customization.md

Added more ideas for retrieval improvement based on common suggestions we give in the issue tracker.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no …
```

Docs: More ideas for improving search results

---

infra/core/host/container-apps.bicep
infra/core/monitor/monitoring.bicep
infra/main.bicep

The referenced AVM modules have several bug fixes and security fixes. This updates them to the latest versions

Update all AVM modules to latest

---

infra/main.bicep

Fixes #2179 and #2139 by
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature …
```

Lower case the ACA container registry name

---

app/frontend/vite.config.ts

Add support for symlinked files.
Without symlink support I get an error when running `azd up` because my repo drive uses a symlink.
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] …
```

Add support for symlinked files

---

.github/workflows/validate-markdown.yml

Use two randomly generated numbers as the name of the markdown file to prevent exploiting the static name of the file as symlink.
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] …
```

Security Update with Bug Fixes

---

README.md

Adding the AI Template learn article to the README.MD Resources section.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] …
```

Update README.md Resources with Learn article

---

docs/monitoring.md
evals/evaluate_config.json

Fixes the image URL for monitoring doc
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... …
```

Fix screenshot for Monitoring doc

---

CONTRIBUTING.md
app/frontend/src/i18n/config.ts
app/frontend/src/locales/it/translation.json
docs/customization.md

Added support for italian language for the platform
```
[ ] Yes
[ ] No
```
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[X] Feature
[ …
```

Added support for italian language

---

app/backend/requirements.in
app/backend/requirements.txt

We previously brought in numpy as it was recommended by the openai package, as a way to speed up embeddings. However @tonybaloney made a change to openai so that it can achieve the same embedding performance without numpy, woot! We can now remove the numpy dependency and we should not see a decrease in embedding performance during data ingestion.
Fixes #2282 
```
[ ] Yes
[X] No
```
check the …

Upgrading openai and removing numpy dependency

---

app/backend/requirements.txt

The previous prompty had a performance issue, especially when called from the root of the repository (like for running tests). That issue is now fixed, so let's upgrade to the new version.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] …
```

Upgrade prompty

---

app/backend/app.py
app/backend/approaches/approach.py
app/backend/approaches/chatapproach.py
app/backend/approaches/chatreadretrieveread.py
app/backend/approaches/chatreadretrievereadvision.py
app/backend/approaches/retrievethenreadvision.py
app/backend/chat_history/cosmosdb.py
app/backend/decorators.py
app/backend/prepdocslib/blobmanager.py
app/backend/prepdocslib/csvparser.py
app/backend/prepdocslib/embeddings.py
app/backend/prepdocslib/filestrategy.py
app/backend/prepdocslib/htmlparser.py
app/backend/prepdocslib/jsonparser.py
app/backend/prepdocslib/listfilestrategy.py
app/backend/prepdocslib/parser.py
app/backend/prepdocslib/pdfparser.py
app/backend/prepdocslib/searchmanager.py
app/backend/prepdocslib/textparser.py
app/backend/prepdocslib/textsplitter.py
evals/safety_evaluation.py
pyproject.toml
scripts/auth_init.py
tests/conftest.py
tests/e2e.py

This PR updates Ruff to target 3.9+ and removes a lot of typing imports that aren't needed from Python 3.9

Upgrade syntax to Python 3.9

---

docs/evaluation.md

Quick fix to remove a paragraph in docs that is not needed.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content …
```

Remove outdated docs

---

evals/requirements.txt

Upgrade packages to versions that have Windows-related fixes.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Documentation content …
```

Update evals requirements

---

docs/reasoning.md

Update doc listing which is outdated.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... …
```

Update reasoning.md with all models
