infra/main.bicep
I noticed that the storage container name var wasn't being used and took the opportunity to rename the var to be clear this is storage container and not some other type of container (docker etc)
=> Update to use storageContainerName var

azure.yaml
fix: https://github.com/Azure-Samples/azure-search-openai-demo/issues/109
azd version 0.8.0 packs the application before creating azure resources (when running azd up) Then `azd deploy` use the output from that packing to publish the app to Azure. The `predeploy` hook is not valid anymore on this scenario to include the frontend to the backend. Instead, we need to switch to use `prepackage` for the backend service, so the frontend is attached before creating the package.
=> Update hooks for azd 0.8.0

scripts/prepdocs.ps1
Update prepdocs.ps1 to avoid `SetEnvironmentVariables` on blank lines. This makes it more inline with prepdocs.sh.
[ ] Yes
[x] No
[x] Bugfix
Fixes #213
=> Avoid setenv on blank lines

infra/main.bicep
Listing and creating search indexes requires that the user has either Owner or Search Service Contributor RBAC roles. For cases where the user is not subscription owner, this change makes things work by adding the Search Service Contributor role for the user running "azd up".
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> Fix non-subscription owner scenarios by adding Search Service Contributor role

README.md
clarify that azd init also initializes a git repo and you do should not in fact clone the repo.
I am used when I start working on a project in github to just clone the repo, but the suggested way to initialized this project in the documentation is the command `azd init`. It was not clear to me before running it that this command already initializes a git repo, maybe this is useful for others.
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> [docs] Clarify that azd init already clones the repo

infra/core/ai/cognitiveservices.bicep, infra/main.bicep
The Azure OpenAI service has a new version of the ARM template contract that supports specifying individual capacities for deployments. Updating Bicep files to use that and avoid errors from trying to provision more than the default capacity.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> Updating Bicep files to use new OpenAI capacity settings in new ARM API version

infra/main.parameters.json
If you want to re-use an existing OpenAI deployment, and it has a different name from the default, the azd env variables have no effect on the deployment. This PR passes the azd env variables referenced in the README through the bicep deployment.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
Follow the README instructions for testing an existing OpenAI deployment, but with a different name from the default. …
=> Add deployment parameters to re-use OpenAI Deployments

infra/main.bicep, infra/main.parameters.json
Allow usage of existing ChatGPT and GPT deployments not using the names 'davinci' or 'chat'
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
1. Set AZURE_OPENAI_CHATGPT_DEPLOYMENT to another value besides 'chat'
2. Set AZURE_OPENAI_GPT_DEPLOYMENT to another value besides 'davinci'
Deploy and validate the deployment succeeds
1. Set AZURE_OPENAI_CHATGPT_DEPLOYMENT to an empty string
2. Set AZURE_OPENAI_GPT_DEPLOYMENT to an empty string …
=> Allow usage of existing OpenAI model deployments

README.md
moving a line because AZD no longer asks for location as part of `azd init`-- it's asked during `azd up`
=> update readme to reflect `azd init` behavior 

app/backend/requirements.txt
Flask 2.2.5 and 2.3.2 include a fix for CVE-2023-30861: When all of the following conditions are met, a response containing data intended for one client may be cached and subsequently sent by the proxy to other clients.
=> Update Flask version

app/backend/app.py
Fixes #277 
Currently, if you upload a file to blob storage that has a non-ascii character, it will fail once app service tries to return it in a response. This appears to be due to the setting of filename in Content-Disposition header to a string that contains non-ascii characters.
Fortunately, flask already has send_file which takes care of that issue:
https://flask.palletsprojects.com/en/2.3.x/api/#flask.send_file
See implementation here:
https://github.com/pallets/flask/blob/fae889d467a0a19385978f7e979234771a0eb10d/src/werkzeug/utils.py#L463
So I modified the content_file function to use send_file instead, with an io.BytesIO object built from the blob content. I deployed to App Service and it does seem to fix it.
```
[ ] Yes
[X] No
```
What kind of change does this Pull Request …
=> Change content_file to use flask.send_file instead

infra/core/ai/cognitiveservices.bicep, infra/main.bicep
This will allow users to be able to specify a sku object when referencing a deployment.
=> Expose deployment sku object

app/backend/app.py
Unfortunately, the Python SDK DictMixin doesn't support the "in" operator. I've sent a PR to fix it: https://github.com/Azure/azure-sdk-for-python/pull/30846
This PR updates the code to use has_key() instead, which is defined for the DictMixin and thus the Blob. That method is considered deprecated for proper python dicts, so it'd be nice to use "in" in the future.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Run ./start.sh
* Click on a citation
=> Use has_key instead of in operator

app/start.sh, scripts/prepdocs.sh
It's generally safer to use `python3` than `python` since the latter is an alias (and does not work on my Mac). `python3` should exist, however, if Python 3 is involved.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Run `azd up` on Mac
* Don't see error about python: command not found
=> Update prepdocs.sh to use python3

infra/main.bicep, infra/main.parameters.json
This PR proposes a slightly simpler way of passing in default values to azd for the gpt parameters. It seems to work for me, but I'd love confirmation from someone on azd team (@vhvb1989) that this functionality is expected to work.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
*  Run azd up on a fresh environment
*  Run azd up on a fresh environment but with gpt names overriden via azd env set
=> Use other approach for specifying default values

infra/main.bicep
Today, Azure disabled new deployments of text-davinci-003, so deployments will fail with an error:
"DeploymentModelNotSupported: Creating account deployment is not supported by the model 'text-davinci-003'. This is usually because there are better models available for the similar functionality."
This change does the minimal change to get deploys to work, swapping text-davinci-003 with gpt-35-turbo. Unfortunately, it really does not do that well on generating search queries, at least with our current prompt, so the chat interface isn't working well. Perhaps we should default to the "Chat" tab until it's worked out.
```
[X] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no …
```
=> Change davinci to gpt35-turbo

infra/main.bicep
This PR uses the location picker functionality for *just* the Open AI resource group location.
That allows us to constrain the locations to just the supported ones, so that folks dont find out after a long deploy about a bad location selection.
This also makes it easy for folks to pick a different location for OpenAI than their main location, which came up in a recent issue.
Here's what the picker looks like - it comes up after packaging but before provision:
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Run azd up
=> Use location picker for openAI

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This PR updates the dev container to use a Python 3.10 base image, instead of the universal bullseye. It subsequently removes the Python feature, since it's slow. The feature was also using "os-provided" as the Python version, which is problematic on machines that have bad Python installs (like mine!). It's a more consistent environment to use the Docker's Python.
(Related issue: #343)
A similar change was made in the Python azd templates a while back:
https://github.com/Azure-Samples/todo-python-mongo-terraform/blob/main/.devcontainer/Dockerfile
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature …
```
=> Use Python 3.10 base image

app/frontend/src/index.tsx, app/frontend/src/pages/NoPage.tsx, app/frontend/src/pages/oneshot/OneShot.tsx, app/frontend/vite.config.ts
* This PR introduces basic code splitting in the frontend:
* Updated react-router-dom hash router to 6.4 API
* Lazy routing to 'q&a' and 'not found' pages. 
* 'Layout' and 'Chat' aren't lazy loaded because that's our initial page.
* Configured rollup manual chunking in vite. _This also gets rid of the 'chunks over 500kb' vite warning_.
* @fluentui/react-icons goes to its own chunk ('fluentui-icons')
* @fluentui/react goes to its own chunk ('fluentui-react')
* Other node_modules dependencies go to a 'vendor' chunk
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
``` …
=> Frontend basic code splitting

infra/core/host/appservice.bicep, infra/main.bicep
This PR enables PYTHON_ENABLE_GUNICORN_MULTIWORKERS on App Service. When Oryx sees that, it will auto configure gunicorn to use a worker count based off the formula of CPU_COUNT * 2 + 1. This should hopefully resolve issues like #272.
Here's Oryx docs about the config option:
https://github.com/microsoft/Oryx/blob/5239b0416cdddcf5bf0aef6703eb339efa865d67/doc/runtimes/python.md?plain=1#L101
The other approach is for us to specify our own startup script that does the same thing (as I describe in https://github.com/Azure-Samples/azure-search-openai-demo/issues/272#issuecomment-1589303445), but for now, this is the quickest fix.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[ ] …
```
=> Tell Oryx to configure gunicorn workers dynamically

README.md
SSL error keeps cropping up, so I've added a link to my favorite fix.
I also amended the note about deploy issues, as I encountered it last night, and I think folks just aren't waiting long enough. Azd says the deploy is done before the server is necessarily started, as I think App Service is working on an availability API or some such.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
=> Add more to troubleshooting section

infra/abbreviations.json, infra/main.bicep, infra/main.parameters.json
This allows the bicep to respect the values ( AZURE_RESOURCE_GROUP & AZURE_SEARCH_SERVICE) manually entered in the .azure/.env file should they be required.
```
[ ] Yes
[X ] No
```
```
[X ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
1. Run `azd up` on a new environment
1. Update the values AZURE_RESOURCE_GROUP and AZURE_SEARCH_SERVICE in the `.azure/.env` file. 
```
```
Verify that the following are valid.
* Verify that the full product was created appropriately after …
=> Respect ENV values for resource group and index name

.github/workflows/python-test.yaml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, app/backend/app.py, app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/readdecomposeask.py, app/backend/approaches/readretrieveread.py, app/backend/approaches/retrievethenread.py, app/backend/langchainadapters.py, app/backend/lookuptool.py, pyproject.toml, requirements-dev.txt, scripts/prepdocs.py
This PR runs ruff, an industry standard linter, over all Python files. It also adds it to pre-commit hooks and GitHub actions. 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Run app/start.sh, local server should be fine.
=> Run ruff, add to precommit

.vscode/launch.json, README.md, app/backend/app.py, app/backend/approaches/approach.py, app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/readdecomposeask.py, app/backend/approaches/readretrieveread.py, app/backend/approaches/retrievethenread.py, app/backend/core/modelhelper.py, app/backend/gunicorn.conf.py, app/backend/langchainadapters.py, app/backend/lookuptool.py, app/backend/main.py, app/backend/requirements.txt, app/start.ps1, app/start.sh, infra/main.bicep, requirements-dev.txt, tests/conftest.py, tests/test_app.py
This PR ports the app to Quart, a Python ASGI web framework. 
Flask is a WSGI framework, which is synchronous. That means that when a request comes in, the server will wait for the request to be processed before it can handle another request. We have added support for multiple gunicorn workers/threads, but they can still easily be blocked by a long-running request. Each /chat request makes 4 API calls, which take from 0.2-7 seconds each.
Quart is designed with the same API as Flask, with a few changes needed for asynchronous support. Most of my changes are the addition of await/async. For the Azure SDK calls, I used the async versions of the clients (imported from `.aio`). For the OpenAI API calls, I used the async versions of the functions (`acreate` instead of `create`).
For deployment …
=> Port to Quart

app/backend/gunicorn.conf.py, locustfile.py, requirements-dev.txt
WIP, loadtest for Locust framework.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* pip install locust
* locust
=> Sample Locust loadtest

.devcontainer/devcontainer.json, README.md, app/frontend/vite.config.ts, app/start.ps1, app/start.sh
Port 5000 doesn't work well on many Macs due to a system process that uses 5000. You don't even get a port conflict error, it just silently fails to load :( I would love to not have to constantly change start.sh when I work on this repo, so I propose my favorite port, 50505.
This PR also removes the command the opens the browser. That command opens the browser before the app starts up, so you end up having to reload it anyway, and you have a moment of thinking it's broken. I think it's better to just click on the URL and open it once it's running.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature …
```
=> Change to port 50505

app/backend/gunicorn.conf.py
This PR updates gunicorn.conf.py to have a timeout of 230, the same as the App Service global timeout (due to load balancers: https://learn.microsoft.com/en-us/troubleshoot/azure/app-service/web-apps-performance-faqs#why-does-my-request-time-out-after-230-seconds).
I don't think this improves performance, but at least it is less misleading to see 600 and think that's how long you'll get. 
timeout docs here: 
https://docs.gunicorn.org/en/stable/settings.html?highlight=timeout#timeout
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Deploy, app should run
=> Gunicorn timeout

infra/main.bicep
This PR updates @allowed per the regions in:
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#model-summary-table-and-region-availability
This will allow devs to pick regions that aren't as overloaded as the originally allowed regions, like southcentralus.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
*  azd up, see picker display all the options, choose one and deploy
=> Update main.bicep with more allowed regions

app/backend/approaches/chatreadretrieveread.py, scripts/prepdocs.py
This PR address some of the recent bugs
1. Users experience 401 during index build.
- Refresh token every 5 minutes for open ai calls
2. Suggestion prompt does not work
- Gpt turbo do not handle lengthy system prompts. Moved document sources to user conversation
```
[ ] Yes
[x ] No
```
```
[ x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Address recent bugs

README.md
Per #166 and internal inquiries from CSAs, developers would like better cost estimates. This PR expands the cost estimate section to include a link to the Azure pricing calculator. I had to put in some estimates there about number of questions per month (for the OpenAI resource), but generally, ACS seems to be the more significant cost. It actually gave me a higher cost than what I saw in my budget, so I'm not sure about the discrepancy. 
Please take a look at my pricing link and see if you agree with how I configured it.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please …
```
=> Add more details to costs section

README.md
This PR makes some README adjustments based off debugging session with Connor.
Specifically, Connor was trying to make it work without running azd up, so I'm adding more detail to that bullet point to try to clarify its necessity.
I also changed `az account show` to `az ad signed-in-user show` as that seems to be the right way to get a principal ID that works in multi-tenant situations.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
=> Update README.md based on Connor's flow

app/backend/app.py, infra/main.bicep, tests/conftest.py
This PR is inspired by debugging session with @connorwehrum - he was getting an unauthorized error on cognitive search, but the real issue is that he had never created a cognitive search and had no relevant environment variables set. I think it would be better if the code failed immediately when these env variables are not set. This should only affect users who are using something outside of the typical azd flow.
It may break people who didn't have these values set but were successfully using the defaults?
```
[X] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
* Run …
=> Remove defaults for getenv

infra/main.bicep
I was trying to deploy the sample, but it was difficult to find an Azure region that would support `text-embedding-ada-002`, and had available OpenAI quota in my subscription, and supported the `Standard_ZRS` storage type. Although ZRS is probably important for production scenarios, using zone redundant storage seems unnecessary for getting started with the sample and unnecessarily limits the user's region options.
```
[ ] Yes
[X] No
```
What kind of change does this Pull Request introduce? Change storage type used when deploying via `azd up` from `Standard_ZRS` to `Standard_LRS`.
```
[X] Bugfix
[ ] Feature
```
```
azd …
```
=> Use `Standard_LRS` instead of `Standard_ZRS`

scripts/prepdocs.py
- recursively read the data directory
- @TODO/SUGGEST - may be worth to think about using the sub directory information for enriching the index and/or use it for access control (e.g., subdirectory names may be named like the Azure AD Group for access control)
* Ability to bring subfolder structure into data directory for better arranging the data, at least on the directory level for now
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ x] Feature
```
*  Run prepdocs on the data directory where content is arranged within subdirectories
```
cd …
```
=> Allow for subdirectory structure within data directory

.github/workflows/stale-bot.yml
This adds a daily bot to mark issues and PRs that have had no activity for >60 days as stale.
Users have the opportunity to respond or close.
This PR uses a date of `-1` for closing, which means it won't close the issues. We can tweak this in future to actually close the issues and PRs automatically
=> Create stale-bot.yml for tidying up backlog

README.md, app/backend/app.py
This PR adds details on how to use logs both locally and in App Service. People need this for debugging issues, its coming up a lot on issues. I made a little video to help as well.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
=> Update README.md with logging info

README.md, infra/main.bicep, infra/main.parameters.json
This PR makes it easier to re-use a search service, by making it possible to specify everything via `azd env set` and writing it all out clearly in the README.
Hopefully helps with https://github.com/Azure-Samples/azure-search-openai-demo/issues/586
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Try a new azd up with existing search resource, following the README instructions
* Also try a standard azd up with all new resources
*
=> Make it easier to re-use a search service

.github/workflows/azure-dev-validation.yaml
Reduces the scope of the GitHub action for checking bicep to run if someone has changed anything in the infra folder.
Will make CI faster for everyone
=> Only validate bicep on changes to infra folder

infra/main.bicep
There are 3 more supported regions for gpt35-turbo 0613 and ada embeddings v2
=> Adding more regions

app/frontend/src/authConfig.ts, app/frontend/src/components/LoginButton/LoginButton.tsx
* Relative redirect URIs were being passed to token fetching methods. This resulted in the following error:
```
{ "error": "invalid_client", "error_description": "AADSTS500116: The reply uri specified in the request is not a valid URL. Allowed schemes: '*'.\r\nTrace ID: 30ef56ba-316c-46fe-bb75-8767e39a4a00\r\nCorrelation ID: d53vsvr51-30f8-4cf6-bf1e-83e55a6s4db5c5\r\nTimestamp: 2023-10-12 04:28:06Z", "error_codes": [ 500116 ], "timestamp": "2023-10-12 04:28:06Z", "trace_id": "30ef56ba-316c-46fe-bb75-8767e39a4a00", "correlation_id": "d53vsvr51-30f8-4cf6-bf1e-83e55a6s4db5c5" }
```
* Use absolute redirect URIs that include the scheme to resolve this issue
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, …
```
=> Use absolute redirect uris for login and fetching tokens

scripts/prepdocs.ps1, scripts/prepdocs.sh
* Commit [c8b8486](https://github.com/Azure-Samples/azure-search-openai-demo/commit/c8b8486d68527026b0660a3a75cc4e5e376793c1) removed two command line arguments to the `prepdocs.sh` and `prepdocs.ps1` scripts which break the document loading process for users of the external OpenAI connection. This has been addressed in the open issue #676 
* I added the two arguments (`openaihost` and `openaikey`) back into the file, fixing the problem.
* Based on the logic of `prepdocs.py` (specifically lines 736-752), I don't believe the change will impact users of the Azure OpenAI service. However, I don't have access, so I cannot test this. 
```
[ ] Yes
[X ] No
```
```
[X ] Bugfix
[ ] Feature
[ ] …
```
=> Add arguments required for OpenAI connection

app/frontend/src/pages/chat/Chat.tsx
After updating my code after recent change (PR to fix chat history context bug, #778), I found that I was getting `TypeError: Cannot read properties of undefined (reading '0')` after asking follow-up questions in the chat. This is the same error as #814 and #770, and I believe are likely related.
I enabled "Application Insights" and found this as the stack trace:
```Traceback (most recent call last):
File "/tmp/8dbcf8b8d2431d2/antenv/lib/python3.11/site-packages/opentelemetry/trace/__init__.py", line 573, in use_span
yield span
File "/tmp/8dbcf8b8d2431d2/antenv/lib/python3.11/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 596, in __call__
await self.app(scope, otel_receive, otel_send)
File "/tmp/8dbcf8b8d2431d2/antenv/lib/python3.11/site-packages/quart/app.py", line …
```
=> Fix bug due to "bot" being used instead of "assistant" in Chat.tsx

.gitignore, scripts/prepdocs.py
Running prep docs on every provision is really time consuming, especially if the docs haven't changed.
This PR writes an `.md5` file with an MD5 hash of the files in `data/` when they get uploaded, then every time the prep docs script is re-run that file is checked against the current hash and the file is skipped if it hasn't changed.
I've added those md5 files to gitignore so they don't get committed and they also won't be uploaded.
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
git checkout …
```
=> Store an MD5 hash of uploaded/indexed file and check before prepdocs

README.md
The sample now shows up in the samples browser:
https://learn.microsoft.com/en-us/samples/browse/
However, it apparently grabs the first tag from each category (languages/products) to display in the card, and the current first tags aren't the most informative. This PR makes it so that "python" is the top language and "azure-openai" is the top product, as that seems like what customers would be looking for.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Wait for samples browser to refresh, see card with "Python" and "OpenAI" tags.
=> Reorder tags to optimize for sample browser

app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/retrievethenread.py, app/backend/core/messagebuilder.py, tests/test_chatapproach.py, tests/test_messagebuilder.py
Fixes #851 
This PR fixes an issue where few shots were getting added in the reverse order, but also renames append_message to insert_message since the current naming can lead you to think it defaults to appending at the end.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* I added a test that failed for previous code and now passes.
=> Fix order of few shots sent to MessageBuilder

.vscode/settings.json
This PR excludes various autogenerated files from being visible in File explorer in VS Code. None of these should be something developers need to open.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Make change, see folders vanish!
Before:
After:
=> Add exclude files

CONTRIBUTING.md, app/backend/app.py, app/frontend/src/pages/chat/Chat.tsx, tests/e2e.py, tests/snapshots/test_app/test_ask_handle_exception/client0/result.json, tests/snapshots/test_app/test_ask_handle_exception/client1/result.json, tests/snapshots/test_app/test_chat_handle_exception/client0/result.json, tests/snapshots/test_app/test_chat_handle_exception/client1/result.json, tests/snapshots/test_app/test_chat_handle_exception_streaming/client0/result.jsonlines, tests/snapshots/test_app/test_chat_handle_exception_streaming/client1/result.jsonlines, tests/test_app.py
This PR overhauls the error handling and fixes it in the case of streaming. (Fixes #869)
Now, whenever an error happens, the UI will display a message that contains only the type (class) of the error, versus the entire error message/traceback. Generally, displaying entire error messages to users is considered a security risk, in case they contain private details, so this approach seems like a happy medium. Let me know if you'd prefer to show entire error.
Example of error when asking ChatGPT for unallowed topics:
Example of error when Azure Cognitive Search is above the semantic quota for the month:
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no functional …
```
=> Handle errors better especially for streaming

app/backend/app.py
Fixes #902 
Apparently Windows machines can have an issue where their mime-types registry is messed up, so this code overrides the registry to be correct. I believe it's okay to have this fix for Linux/Mac as well.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Locally, cd app and start.sh
* Deploy to prod and see static assets come in correctly
=> [Bug fix] Fix for mimetypes issue when running local server on Windows machines

app/backend/app.py, tests/snapshots/test_app/test_ask_handle_exception_contentsafety/client0/result.json, tests/snapshots/test_app/test_ask_handle_exception_contentsafety/client1/result.json, tests/snapshots/test_app/test_chat_handle_exception_contentsafety/client0/result.json, tests/snapshots/test_app/test_chat_handle_exception_contentsafety/client1/result.json, tests/snapshots/test_app/test_chat_handle_exception_contentsafety_streaming/client0/result.jsonlines, tests/snapshots/test_app/test_chat_handle_exception_contentsafety_streaming/client1/result.jsonlines, tests/test_app.py
This PR treats the "content_filter" error as a special type and produces a special message that developers can easily customize as they see fit.
In non-streaming case, it returns 400 instead of 500, since it's a user error versus a server error. In streaming case, it's part of a 200-level response, since we can't change the status code of a stream once started.
Unfortunately, the ask approach doesn't trigger this error when it probably should, presumably because the additional context is throwing off the detection (in chat, the first gpt request has no context). The ask tab instead responds with "Sorry, I can't answer that". I will share examples with content safety team as it'd be nice to be able to trigger it.
Fixes #887
```
[ ] Yes
[X] No
```
What kind of change does this Pull Request …
=> [Backend] Add special handling in app.py for content safety filter errors

infra/main.bicep
The field `capacity` can't be directly used at the root level of a deployment object for the cognitive services module.
The module expects either the node `sku` or nothing:
```
sku: contains(deployment, 'sku') ? deployment.sku : {
name: 'Standard'
capacity: 20
}
```
This PR won't change any functionality, as the default value for sku provided by the module is currently equal to the value set in main.bicep.  But fixes the bug for any user trying to use the capacity field with other value, as it is ignored
=> Fix ignored capacity field for openAI deployment

app/backend/app.py
This PR changes the Content-Type of responses from the endpoint **/chat**. Previously, streamed responses where sent as  **text/html; charset=utf-8**, now they would be sent as **application/json**
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Do a request to the **/chat** endpoint and see that the Content-Type is different in the response header
=> set content-type for streamed response

scripts/prepdocslib/searchmanager.py, tests/test_searchmanager.py
Fixes #960 and adds tests. The issue was that later document IDs were overriding earlier ones.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Run pytest
=> [Bug fix] Fix prepdocs logic in uploading docs with more than 1000 sections

README.md, infra/main.parameters.json
Fixes #901 
@achandmsft recommends we default to deploying Application Insights, given the costs are low and benefits are high. I've recently been using "Investigate > Failures" as an alternative to Log Stream and it's quite helpful, it'd be nice to know all developers had that feature when helping them debug.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
*  `azd up` in env that doesnt have AZURE_USE_APPLICATION_INSIGHTS set, then run azd monitor to see dashboard
=> [Infra] Default AZURE_USE_APPLICATION_INSIGHTS to true, so that monitoring is always provisioned

README.md
We currently link to the Python SDK enums but that's actually misleading since we need developers to specify the string values instead. This PR updates the readme to link to a table which has string values and indication of spell checker support.
(This was discovered in debugging session with an Italian developer who had specified the enum code instead of string.)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* We fixed a bad deploy by using the string value.
=> [Docs] Update search internationalization links to table with string values

scripts/prepdocslib/blobmanager.py
Fixes #1068
The default font seemed to work on my system, though I don't now if GPT-4v finds some fonts easier than others.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Run ./scripts/prepdocs.sh on a system that doesnt have those other fonts, See:
```
Splitting 'Financial Market Analysis Report 2023.pdf' into sections
Uploading blob for whole file -> Financial Market Analysis Report 2023.pdf
Unable to find arial.ttf or FreeMono.ttf, using default font
Converting page 0 to image and uploading -> Financial Market Analysis Report 2023-0.png
```
* Load app, …
=> [BugFix] Use default font when a specific font cannot be found

app/backend/core/authentication.py
* The judgment should have verified groups and oids, but the existing judgment criteria only include verifying oid.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
origin line:
```
if (use_oid_security_filter or use_oid_security_filter) and not self.has_auth_fields:
```
There are two 'use_oid_security_filter' before and after
fixed line:
```
if (use_oid_security_filter or use_groups_security_filter) and not self.has_auth_fields:
```
```
```
* ...
* I am sorry that I discovered this logical …
=> bugfix:  fix the same variable was used twice in the judgment

app/backend/core/authentication.py, app/frontend/src/authConfig.ts, tests/test_authenticationhelper.py
* Ensure tokens are refreshed when using easy auth so the full refresh window is used before requiring login again
* Store tokens in local storage so sessions are preserved across tabs
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
*  Validate .auth/refresh is called when logging into the app using the network tab on developer settings
* Validate auth_setup shows localStorage as the msal cache location
=> Update Authentication to use local storage and easy auth refresh

app/frontend/src/pages/chat/Chat.tsx
I get occasional errors from typing tools about this line of code (but not always - not sure why I don't always see it), so this PR explicitly casts it as a ChatAppResponse object.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* `npm run build` shouldn't show any errors
=> Cast event as ChatAppResponse

app/frontend/src/pages/chat/Chat.tsx, scripts/prepdocslib/textsplitter.py, tests/test_prepdocslib_textsplitter.py
* ...
```
[ X] Yes
[ ] No
```
It solves the problem with indexing small documents, where amount of text is less than section_overlap. In this case it's enought to check if  amount of text is less than max_section_length and return only one section without additional processing. 
This approach assumes that the section_overlap < max_section_length
```
[X] Bugfix
[ ] Feature
```
Index document whith amount of text less than max_section_length
```
cd [repo-name]
npm install
```
Index …
=> bug #1152: Fix for indexing small docs

app/backend/approaches/chatapproach.py, app/backend/approaches/chatreadretrieveread.py, tests/test_chatapproach.py, tests/test_chatvisionapproach.py
`functions` is a deprecated argument. We should be using the tools parameter
=> Update to tools parameter

app/backend/app.py, tests/test_app_config.py
This PR fixes an issue introduced by my searchkey PR, where it assumed it could find both the search and vision key at same time. Fixed and added tests.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Run tests
* Run local server in a GPT4-vis environment
* Run local server in a free environment
=> Account for vision key only situation

infra/main.bicep
This PR fixes the App Service level to be based on the final computed level. This will fix the free deployment scenario so that you don't have to manually uncheck the ranker box.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
=> Fix search ranker level

scripts/prepdocslib/embeddings.py
Our prepdocs code was still using the old hack for AD authentication. This PR updates the code to use token_provider, the recommended way.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Run ./scripts/prepdocs.sh while using Azure default auth
=> Use token provider instead of token wrapper

app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/chatreadretrievereadvision.py
This pull request includes changes to the `run_until_final_call` function in two files: `app/backend/approaches/chatreadretrieveread.py` and `app/backend/approaches/chatreadretrievereadvision.py`. The changes involve adjusting the temperature parameter for the OpenAI chat completion function from 0.7 to 0.3. This will affect the randomness of the AI's responses, making them more deterministic and less random.
The ask approach already uses 0.3, so this makes chat match it.
The 0.3 did well in evaluations as compared to current baseline:
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] …
```
=> Change default temp to 0.3 for final chat completion call in chat approaches

infra/core/search/search-services.bicep
fixes #1254 
This pull request includes a change in the `search-services.bicep` file. The change modifies the output of `principalId` to conditionally return an empty string when the `sku.name` is 'free', otherwise it returns `search.identity.principalId`.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Follow free deployment instructions
* Run azd up
=> Only output identity for non-free SKU

infra/core/search/search-services.bicep
I didn't like how non-DRY my last change was, so this PR DRYs it up.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
*  I ran azd provision from a free env and a non-free env
=> Better conditional around searchservice principalId output

scripts/prepdocs.py
The current code produces a DeprecationWarning in 3.12. This change removes the warning. It looks like this is supported for all our supported versions of Python, per reference at:
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Create a 3.12 environment
* Run ./scripts/prepdocs.sh
* Don't see DeprecationWarning
=> Proper event loop setup

docs/gpt4v.md
This clarifies that you must make sure to not use integrated vectorization if you're trying to use GPT-4-vision approach. A customer ran into this today and was perplexed. We could also add an error in prepdocs to warn about it.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
=> Clarify that gpt-4-v cant be used with integrated vectorization

.github/workflows/frontend.yaml, .github/workflows/python-test.yaml
Fix #1356 
- restrict frontend workflow to changes in the frontend folder
- restrict python workflow runs to changes in python files
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] …
```
=> Restrict GitHub workflows run

docs/productionizing.md
Adds a link to the search service size guide, for customers wondering about productionizing their index.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, …
```
=> Update productionizing.md with link to search service size guide

.github/workflows/azure-dev-validation.yaml
This is the change I made in langfuse-on-azure to avoid the error with "resource inaccessible by integration". It's shown in docs at bottom of https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
I also added workflow_dispatch for ease of testing.
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A …
=> Add needed permissions for template-analyzer workflow

scripts/prepdocslib/textsplitter.py, tests/test_prepdocslib_textsplitter.py
Fixes a bug when a section doesn't contain _any_ sentence endings and isn't recursively split correctly. It was being split into one big section and one empty one.
Fixes #1415 
```
[ ] Yes
[x] No
```
```
[ ] Yes
[ ] No
```
```
[x] Bugfix
[ ] Feature
[ ] Code style …
```
=> Ensure there are no zero-length sections for batch API

CONTRIBUTING.md
Added an instruction to Compile the JavaScript. This is required for pytest tests to pass.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api …
```
=> Added an instruction to Compile the JavaScript, required for pytest to pass.

app/backend/approaches/chatreadretrieveread.py
* Typo "Azure Open AI"→"Azure OpenAI"
* https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/approaches/chatreadretrieveread.py * #PingMSFTDocs
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update …
```
=> Update chatreadretrieveread.py (Typo "Azure Open AI"→"Azure OpenAI")

app/backend/approaches/approach.py, app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/chatreadretrievereadvision.py, app/backend/approaches/retrievethenread.py, app/backend/approaches/retrievethenreadvision.py, app/frontend/src/api/models.ts, app/frontend/src/pages/ask/Ask.module.css, app/frontend/src/pages/ask/Ask.tsx, app/frontend/src/pages/chat/Chat.module.css, app/frontend/src/pages/chat/Chat.tsx, tests/test_chatapproach.py
A filtering mechanism based on minimum score criteria for documents. By setting a minimum value for both `search_score` and `reranker_score`. This aims to improve the relevance of documents sent to the AI, that only the most relevant information is sent for further processing.
```
[ ] Yes
[x] No
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if …
=> Add minimum score criteria for AI search results

app/backend/app.py, infra/main.bicep, tests/test_app_config.py
I realized (from an internal bug report) that we were using two different env vars, SEARCH_SECRET_NAME and AZURE_SEARCH_SECRET_NAME. This PR fixes the code to always use AZURE_SEARCH_SECRET_NAME.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature …
```
=> Fix search secret name environment variable for free deploys

scripts/prepdocs.ps1, scripts/prepdocs.sh
Fixes #1477
I haven't tested myself, but it looks correct in terms of the args, and this fix worked for the reporter.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no …
```
=> Correct datalakepath argument in prepdocs.sh and prepdocs.ps1

README.md
Fixes #1468 
Updated pricing estimate. I don't think I've had that error in the pricing this whole time, and I noticed some other incorrect costs in Document Intelligence section, so I wonder if it changed underneath us. Anyway, this version looks reasonable to me.
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an …
=> Update link to pricing calculator to fix Document Intelligence estimation

app/backend/app.py, app/backend/prepdocslib/blobmanager.py, app/backend/prepdocslib/filestrategy.py, app/backend/prepdocslib/listfilestrategy.py, app/backend/prepdocslib/searchmanager.py, app/frontend/src/components/UploadFile/UploadFile.tsx, docs/deploy_features.md, docs/login_and_acl.md, scripts/manageacl.py, tests/conftest.py, tests/test_blob_manager.py, tests/test_manageacl.py, tests/test_prepdocslib_filestrategy.py, tests/test_searchmanager.py, tests/test_upload.py
Fixes #1531 
Possibly fixes #1424
With the recent addition of the user upload feature, it is now possible for a file with the same filename to exist in two places (either the user's storage container or the global content container). I accounted for that in terms of searching and user deletion, but realized that manageacls.py didn't have a way to unambiguously identify what document's ACLs to update. 
So this PR adds a new field "storageUrl" that stores the full Blob storage URL (*not* with any SAS tokens however), and changes manageacls.py to expect a full URL to be passed in. It's slightly more work since you need to go into Blob storage and copy the URL from the portal, but much more clear what document you're trying to ACL.
I also improved logging in manageacls.py so that we can …
=> Adds storageURL field to track file location

app/backend/gunicorn.conf.py
Fixes #1495
The cpu_count() reports 2 which results in 5 workers, but they get killed due to lack of memory. So instead we only use 1 if we detect we're running on free tier.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Code style update …
```
=> Fix gunicorn config to use single worker for free sku

infra/core/ai/cognitiveservices.bicep, infra/main.bicep
This pull request introduces changes to the `infra/core/ai/cognitiveservices.bicep` and `infra/main.bicep` files to add a new parameter `disableLocalAuth` to the cognitive services configuration and to set its value in the main configuration to true.
This improves security since it means that only keyless auth can be used with the OpenAI service.
```
[ ] Yes
[X] No
```
check the box below and …
=> Disable OpenAI key access

app/backend/core/authentication.py, app/backend/prepdocslib/searchmanager.py, tests/test_authenticationhelper.py, tests/test_searchmanager.py, tests/test_upload.py
Fixes #1591 
This PR escapes apostrophes using the strategy suggested in the Azure AI Search docs, which I've linked in the code. I changed the tests to have apostrophes in their names, but I could also duplicate the existing tests if we want it to be One Test per One Bug.
I manually tested this by uploading a PDF with an apostrophe in the title, asking a question about it, and verifying the PDF loaded.
```
[ ] Yes
[X] No
```
which includes deployment, settings and usage instructions. If text or screenshot …
=> Escape single quote marks for search filters

infra/main.bicep
This PRs disable key-based API access ("local auth") for Document Intelligence, which is preferred from a security standpoint. We have seen that developers have wanted to keep key access for their OpenAI accounts and have been asked to make it an option, should I also make this an option (via a bool parameter like enableDocIntelligenceKeys defaulting to false?)
```
[ ] Yes
[X] No - at least it shouldnt be for our core repo
```
which includes deployment, settings and usage instructions. If text or …
=> Disable key auth for Azure Document Intelligence

app/backend/prepdocslib/textsplitter.py, tests/test_sentencetextsplitter.py
Closes #1667.
This PR fixes the overlap calculation issue reported in #1667.
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] …
```
=> Fix overlap percentage calculation

.devcontainer/devcontainer.json
Fixes #1749 
The powershell feature is causing Codespace builds to break, seems related to https://github.com/PowerShell/PowerShell/issues/23975
I think we rarely need powershell inside the devcontainer, since you can use bash scripts there. I mostly use it when I'm testing what powershell scripts would do on a Windows machine, to avoid me having to open a DevBox for Windows.
```
[ ] Yes - Maybe, if developers are actually using powershell inside devcontainer/Codespace?
[ ] No
```
which includes …
=> Remove powershell feature

infra/core/storage/storage-account.bicep
This resolves a security alert. We currently still have NetworkAcls:Allow even when public access is set to Disabled. This PR changes them to Deny in that case. 
I have tested this in my Vnet branch and I was able to view citations from inside the VM. I will now test with a non-Vnet branch and ensure nothing changes there.
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial …
=> Set ACLs to Deny for storage

app/frontend/package.json
Fixes #1788 
The additional argument is necessary due to a vite/Docker interaction issue detailed in:
https://github.com/vitejs/vite/issues/16522
It's also possible to specify the host in vite.config.ts:
https://github.com/Azure-Samples/rag-postgres-openai-python/commit/966022375e9f999c36d7cce66aea24e9b0892e89
But this approach (in package.json) might be more obvious, if someone needs to change it.
```
[ ] Yes
[X] No
```
which includes deployment, settings and usage instructions. If text or screenshot need …
=> Fix vite by adding host

docs/data_ingestion.md, scripts/prepdocs.ps1, scripts/prepdocs.sh
* Prepdocs scripts require certain environment variables to be set.
* Prepdocs has many additional arguments, and not all of them map to environment variables. For example, `--removeall` is used to delete documents from the search index.
* Support passing through these additional documents (e.g. `./prepdocs.ps1 --removall`) without requiring environment variables.
```
[X] Yes
[ ] No
```
check …
=> Prepdocs: Support additional args

app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/chatreadretrievereadvision.py, app/backend/approaches/retrievethenread.py, app/backend/approaches/retrievethenreadvision.py, app/frontend/src/api/models.ts, app/frontend/src/i18n/tooltips.ts, app/frontend/src/pages/ask/Ask.tsx, app/frontend/src/pages/chat/Chat.tsx, tests/conftest.py, tests/snapshots/test_app/test_chat_seed/client0/result.json, tests/snapshots/test_app/test_chat_seed/client1/result.json, tests/test_app.py
This adds a seed parameter. This was a bit tricky as we need to send in null if no seed is desired. I did that by only sending the seed parameter over the wire if its explicitly set in the frontend, and defaulting the value to None in Python.
Fixes #1344
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external …
=> Add an optional seed parameter

docs/README.md
Think `private.md` was renamed to `deploy_private.md` but the link was not updated here.
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature …
```
=> Fixed link to private access markdown page

app/backend/app.py, infra/main.bicep, infra/main.parameters.json, scripts/prepdocs.ps1, scripts/prepdocs.sh, tests/test_app_config.py
Since adding AZURE_OPENAI_API_KEY as an optional env variable several months ago, many developers have had errors when running and deploying the app, due to that variable existing from other tutorials/templates. This PR changes the variable to a much more unique name.
Fortunately, I never documented it in this repo, since that change was to support our use of the Azure OpenAI Proxy in workshops, so I do not believe many developers are using it for production. I will note in release notes as a backwards compatible change.
```
[X] Yes - for any developer who'd been relying on it. Should be minimal given its 2 months old and …
```
=> Rename Azure OpenAI key environment variable

README.md, samples/chat/README.md
fix #1882 
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> Fix broken paths

app/frontend/src/components/QuestionInput/QuestionInput.tsx
This change addresses an issue where pressing the Enter key during IME (Input Method Editor) composition would accidentally submit the message. By adding logic to track the IME composition state, the application now only submits the message when the Enter key is pressed outside of an IME composition session. This prevents unintended message submission for users who input text in languages that require IME.
```
[ ] Yes
[x] No
```
which includes deployment, settings and usage instructions. If text or …
=> Prevent IME-related accidental message submission on Enter key press

README.md, docs/productionizing.md, infra/main.parameters.json
This PR makes the default deploy cheaper by using the basic tier of search service.
The main drawback of this is that you can't change tiers of existing search services, so:
1) Anyone who is updating to this code will need to explicitly set their sku to standard, via azd env set AZURE_SEARCH_SERVICE_SKU standard
2) Anyone who starts off with basic and wants to upgrade skus will have to either re-index their data ($$) or copy their data over (there are scripts to do this, but they take some effort to run)
However, we are trying to reduce default costs of our templates, so that developers have less surprises in their bills.
```
[X] Yes …
```
=> Reduce cost by defaulting to basic tier of search service

app/frontend/package-lock.json, app/frontend/package.json, app/frontend/src/components/AnalysisPanel/ThoughtProcess.tsx, app/frontend/src/index.tsx
With upcoming changes potentially adding JS (#1790), I wanted to make sure we didn't have any unneeded JS. I used the rollup-plugin-visualizer to visualize the current package sizes:
I realized that the syntax highlighter was bringing in *all languages* which added a ton to our overall size. I've adjusted it to only bring in the language we need, JSON.
Now its footprint is much smaller:
This brings app/backend/static to ~13M, down from 16M.
```
[ ] Yes
[X] No
```
which includes deployment, settings and …
=> Reduce JS size by using more specific import for react-syntax-highlighter

infra/main.bicep
This PR runs `az bicep format -f infra/main.bicep`
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] …
```
=> Run format on main.bicep

scripts/adlsgen2setup.py, scripts/adlsgen2setup.sh
I was following the instructions to add in the 'Upload Documents' feature to this demo. I ran into a few issues when running the scripts. 
The changes are minor. But they should be reviewed on your end. It's not much, but it's what I needed to get things rolling past errors.
```
[ ] Yes
[x] No
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if …
=> Adlsgen2 fixes

azure.yaml
When we added optional ACA deployment, we changed `prepackage` to `prebuild`, but azd us not calling prebuild for App Service deployments, so its not building the static folder. So App Service deployments only work if you've somehow built that static folder otherwise, like by having run the local server before the deploy. 
FYI @1yefuwang1 
```
[ ] Yes
[X] No
```
check the box below and notify …
=> azure.yaml improvements: remoteBuild option, prepackage for App Service

app/backend/approaches/approach.py, app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/chatreadretrievereadvision.py, app/backend/approaches/retrievethenread.py, app/backend/approaches/retrievethenreadvision.py, docs/localdev.md
This PR makes it easier for developers who want to use local models in development, either for cost reasons or comparison reasons. I tested with llama3.1:8b from Ollama, which works even for the Chat tab, as well as phi3.5 which works only for the Ask tab (no function calling).
The primary change is that I enabled the use of the GPT tokenizers even for non-GPT models. This means that the token counting will be inaccurate for local models, but that isn't practically an issue unless you have very long conversations.
```
[ ] Yes
[X] No
```
This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/ …
=> Changes for easier working with local models

infra/main.bicep
The container apps PR accidentally changed two roles that didnt need to change, the roles for the search service principal ID. These roles are needed for integrated vectorization feature.
FYI @1yefuwang1 
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] …
```
=> Fix roles for integrated vectorization

app/backend/prepdocs.py, app/backend/prepdocslib/integratedvectorizerstrategy.py, app/backend/prepdocslib/searchmanager.py, app/backend/requirements.in, app/backend/requirements.txt, docs/data_ingestion.md, docs/deploy_features.md
Fixes #1825
Updates to latest Azure AI search package and specify embedding model name and dimensions
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no …
```
=> Updates to integrated vectorization

app/frontend/src/i18n/config.ts, app/frontend/src/locales/ptBR/translation.json
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
See …
=> feat: add Portuguese (pt-BR) translations and update i18n configuration to include the new language

infra/main.bicep
Fixed an issue where an error would occur when attempting to deploy the `monitoring` module if the environment variable `AZURE_USE_APPLICATION_INSIGHTS` was set to `false` during provisioning.
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] …
```
=> Fix: Provisioning failure issue

app/frontend/src/pages/chat/Chat.module.css
limit .chatContainer height and expand chatMessageStream
fix #2002 
prevent the outside scrolling bar by limiting the total height.
extented the chatMessageStream to width 100%, and use padding to constrain the chat messages in center. (in order to allow user to scroll in wide range)
```
[ ] Yes
[x] No, just css style change
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external …
=>  Fix scrolling bar issue for long content in chat UI

app/backend/prepdocslib/filestrategy.py
use lower() to match upper file extension name
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] …
```
=> When uploading file with upper case extension name, cannot match correct parser

README.md, azure.yaml, docs/azure_app_service.md, docs/azure_container_apps.md, docs/deploy_private.md, infra/main.parameters.json
Improve the developer experience for new developers by using ACA for faster deployment.
The biggest drawback of this change is that existing developers will need to keep a code change to azure.yaml in order to keep using App Service, since we can't do this with solely environment variables.
```
[X] Yes - existing devs need to follow app service guide to keep using it.
[ ] No
```
check the box …
=> Switch to ACA by default

app/frontend/src/components/Answer/AnswerParser.tsx
This PR addresses a regression introduced in PR #2056 that caused issues with filenames containing whitespace. The regular expression used to validate citation filenames has been updated to allow internal whitespace, ensuring proper handling of such filenames.
```
[ ] Yes
[x] No
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an …
=> Fix regression from PR #2056: Allow whitespace in citation filenames

app/frontend/src/i18n/config.ts, app/frontend/src/locales/nl/translation.json
This update adds support for the Dutch language in the application. It includes translations of the user interface and labels to Dutch, enabling a more accessible experience for Dutch-speaking users.
```
[ ] Yes
[ X ] No
```
```
[ ] Yes
[ X ] No
```
```
[ ] Bugfix
[ X …
```
=> feat: Add Dutch (nl-NL) translations.json and update config.json

app/frontend/src/i18n/config.ts, app/frontend/src/locales/da/translation.json
This update introduces Danish language support in the application, including translations of the user interface and labels into Danish by a native speaker. This enhancement provides a more accessible experience for Danish-speaking users.
```
[ ] Yes
[x] No
```
```
[ ] …
```
=> feat: Add Danish (da-DK) translations.json and update config.json

infra/main.bicep
Related to #1484, fixes one comment in it.
Customers are getting emails that the gpt-4o model version will be deprecated soon.
This PR updates it to the latest, which fortunately is in the same regions as the old version.
I tried to also update the model version for gpt-35-turbo but the availability is fairly different. I think it'll be easier to port to gpt-4o-mini, region-wise, so saving for a different PR.
To test this, I re-ran `azd up` with the new version and it went through successfully. App works correctly for both text and vision modes.
```
[ ] Yes
[X] No
```
This repository is referenced by [this …
=> Update model version for gpt-4o to latest

.vscode/launch.json, docs/localdev.md
Fixes #1339, fixes #2033 
We no longer need to have the azd dotenv task as a dependency, as our code in main.py loads in the azd environment dynamically. Given the issues caused loading that task in Codespaces, it's better to remove it entirely.
I also went ahead and added a nice combo configuration and some docs while I was at it.
```
[ ] Yes
[X] No
```
check the box below and notify the …
=> VS Code debug launch improvements: remove azd extension dependency, add compound, add docs

README.md
The cost estimation link is for App Service, but we now default to ACA.
Also, the services list was missing Container Registry, which is the priciest part of ACA at low volumes ($5/month minimum).
Please double check my pricing link is reflecting reasonable estimates.
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an …
=> Update cost estimation guide

.vscode/launch.json, app/backend/load_azd_env.py
Overriding the env vars in then vscode launch.,json ""env": .." section does not work because of load_azd_env.py
always gives the dot env presence. Therefore i changed load_dotenv(env_file_path, override=True) to
load_dotenv(env_file_path, override=False) to let the env var win in favor to dot env file setting
=> let env var overrule .dot env setting

docs/azure_app_service.md
```
[ ] Yes
[ X ] No
```
```
[ ] Yes
[ X ] No
```
```
[ X ] Bugfix
[ ] Feature
```
See …
=> Fix Broken Links in azure_app_service.md

docs/data_ingestion.md
Update incorrect file path to chunking algorithm in data_ingestion.md
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation …
```
=> Update path to chunking algorithm in data_ingestion.md

app/backend/app.py, infra/core/host/appservice.bicep, infra/core/host/container-app-upsert.bicep, infra/core/host/container-app.bicep, infra/core/host/container-apps-auth.bicep, infra/main.bicep
Fixes #2181 
This PR configures built-in auth for the new default deployment target, Azure Container Apps.
It also configures CORS correctly, based on Matt's old PR with a few fixes, so that logout works as expected.
This uses a currently undocumented way of connecting the token storage container, which uses managed identity instead of keys. I've asked the team about timeline for documenting that feature. Note that built-in auth for ACA is considered a preview feature.
One potential issue: if you've got an app with built-in auth deployed already, then our frontend code will only logout the user from MSAL, not from built-in auth, because it checks for an MSAL token first. We could potentially change that to be based on whether the ".auth/me" endpoint returned anything.
When developers …
=> Configure built-in auth for Azure Container Apps

app/frontend/src/components/QuestionInput/QuestionInput.tsx
Currently, the send button is disabled when login is required, even if the user is already logged in (see #2071). While chatting can still be done via the Enter key, the disabled button is redundant since the text input box is already blocked when the user is not logged in. This unnecessary check has been removed to address this bug.
```
[ ] Yes
[ X ] No
```
check the box below and notify the …
=> [Bugfix] The "send" button for chat should be enabled for logged in users

infra/main.bicep
I discovered that logout for ACA built-in auth was still resulting in a CORS error, and it seemed to be due to an empty string domain in the CORS list. This PR changes the bicep variables so that we remove duplicate and empty domains for the domains that are passed to ACA/AppService. Previously, we only removed that for the environment variable version of the domains (the one used by the CORS extension).
```
[ ] Yes
[X] No
```
which includes deployment, settings and usage instructions. If text or …
=> Remove empty origins for array version of CORS domains too

app/backend/requirements.txt, docs/azd.md
This issue broke the auth setup:
https://github.com/microsoftgraph/msgraph-sdk-python-core/issues/781
We need tests that run the auth scripts! The CI didn't find the issue, but a mocked test would have.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] …
```
=> Revert upgrade of msgraph-core SDK

app/backend/prepdocslib/pdfparser.py, docs/deploy_features.md, tests/test_pdfparser.py
Fixes #2242 
Unfortunately, the figures extraction doesn't yet work for office documents. This PR makes the flow default to standard ingestion for them. We could also have it error out entirely, like it does now, but with a more helpful message. Am not sure what developers would prefer.
Still working on the unit test
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A …
=> Handle lack of support for docx/pptx/xlsx for media description

infra/main.bicep
Fixes #2218 
We were missing the Content Understanding resource ID for the private endpoint configuration, so this PR adds it in.
I do not currently have a private deployment/ VPN setup, so I haven't been able to verify this fix personally. However, it's the same code we use for the other cognitive service accounts.
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A …
=> Add content understanding to private endpoint

app/backend/prepdocslib/pdfparser.py
This is a tiny PR, I just reamed the variables/reworded comments when I was explaining the image cropping in the recent stream.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring …
```
=> Clearer variables for image cropping code

docs/deploy_existing.md, docs/deploy_features.md, infra/main.bicep
Fixes #2328 due to pending version deprecation
```
[ ] Yes
[X] No - quality should be better/same
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] …
```
=> Default gpt-35-turbo to 0125

.github/workflows/python-test.yaml
Less overhead makes this easier to maintain and enables using hardlinking on Windows runners
The hardlinking warning can be seen here.
https://github.com/Azure-Samples/azure-search-openai-demo/actions/runs/13211586770/job/36885643258
```
[ ] Yes
[x] No
```
```
[ ] Yes …
```
=> Use uv managed python in GHA workflows

locustfile.py
1. The main tasks' steps have names
2. It asks for follow up questions
3. The second chat request randomly picks one of the follow up questions
=> Improve locust test script

docs/login_and_acl.md, scripts/auth_init.ps1, scripts/auth_init.sh
Fixes #2325 and related issues.
At least a few developers have gotten themselves into situations where they've set some auth-related parameters but not others, so I've added checks to the auth_init scripts.
Now developers will see errors like these two:
I also improved the docs, based on o3-mini suggested formatting.
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A …
=> Add auth-related azd env variable checks and improve docs

.github/workflows/python-test.yaml
GitHub Actions deprecates `ubuntu-20.04` image. The image will be fully unsupported by 2025-04-01.
Here is more information: https://github.com/actions/runner-images/issues/11101
This PR changes the version of Ubuntu runner to the latest LTS release 24.04.
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Dependency upgrade
```
See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.
=> Upgrade Ubuntu runner for tests in Github Workflow to `latest`

README.md, docs/productionizing.md, infra/core/host/container-app-upsert.bicep, infra/main.bicep
Fixes #2436 
Thanks to the filed issue, I discovered that we were configuring Container Apps with a higher-than-default CPU core and memory, and a min replica of 1.
Unfortunately, we need the higher CPU and memory, due to our app's needs,
but the app still works fine with a min replica of 0 - it just means a slower start when it needs to scale back to 1 sometimes.
```
[X] Yes - If people are running this in production with these settings, it will reduce the performance of the app. I will note in release notes. I've also added a section to productionizing guide.
[ ] No
```
This repository is referenced by [this …
=> Adjust container apps to scale to zero

scripts/auth_init.py
* Quote parameter when running `azd env set` during auth setup
* This prevents env variables from being interpreted as command line switches, for example when setting values that have `-` in them
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature …
```
=> Add quotes to azd env set

infra/main.bicep
As pointed out by @JBrocket on PR #2443, I did not change the regions list to only the ones that support gpt-4o-mini/text-embedding-ada002 with Standard sku, the current default models. That means that a new developer may pick a region like canadaeast which has no support for the model.
This PR changes the allowed list to the regions for gpt-4o-mini, Standard. Unfortunately, this means that *existing* developers who used other regions will get an error from Bicep, due to their region not being on the allowed list. They will have to manually add it when they see the error.
I talked with the azd team about this, and I only see one good solution to have less region issues: default to GlobalStandard, which has a consistent set of region support. However, to do that, we need to migrate …
=> Reduce list to only the available ones for gpt-4o-mini/Standard

app/backend/prepdocs.py
AZURE_ADLS_GEN2_STORAGE_ACCOUNT is only set when developers are using the ADLS2 strategy, ENFORCE_ACCESS_CONTROL is set for all cases when they want acls.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local …
```
=> Use ENFORCE_ACCESS_CONTROL to decide whether to make acls

docs/deploy_existing.md, docs/reasoning.md
Fixes #2496 by documenting how to set the API version to one that supports the reasoning models.
The other approach is to dynamically default the version in code based on the model selected, but given you already have to use "azd env set" and this is a preview version, I think I prefer the documentation approach.
Also fixes #2495, outdated model names in the documentation.
```
[ ] Yes
[X] No
```
which includes deployment, settings and usage instructions. If text or screenshot need to change in the …
=> Update reasoning docs to include API version

infra/core/storage/storage-account.bicep, infra/main.bicep
Fixes #2478 
This upgrades the Bicep versions of resources. We have another PR to replace storage module with avm storage, but may as well upgrade this module while that's pending. I think we can merge that now/soon though, as avm made the fix we were waiting for.
```
[ ] Yes
[X] No
```
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an …
=> Upgrade Bicep versions of resources

tests/test_authenticationhelper.py
This PR resolves `datetime` deprecation warnings which you can find in the [CI logs](https://github.com/Azure-Samples/azure-search-openai-demo/actions/runs/14526972722/job/40760250284#step:10:349):
```python
tests/test_authenticationhelper.py::test_validate_access_token
/home/runner/work/azure-search-openai-demo/azure-search-openai-demo/tests/test_authenticationhelper.py:56: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
"exp": int((datetime.utcnow() + timedelta(hours=1)).timestamp()),
tests/test_authenticationhelper.py::test_validate_access_token
/home/runner/work/azure-search-openai-demo/azure-search-openai-demo/tests/test_authenticat …
```
=> Resolve datetime deprecation warnings

.github/workflows/python-test.yaml
The latest uv action version requires explicit activation of the uv environment.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] …
```
=> Explicitly activate the uv environment in CI

app/backend/approaches/approach.py, app/backend/approaches/chatreadretrieveread.py, app/backend/approaches/retrievethenread.py, app/frontend/src/api/models.ts, app/frontend/src/components/Settings/Settings.tsx, app/frontend/src/locales/en/translation.json, app/frontend/src/pages/ask/Ask.tsx, app/frontend/src/pages/chat/Chat.tsx, tests/snapshots/test_app/test_ask_rtr_text_agent/agent_client0/result.json, tests/snapshots/test_app/test_ask_rtr_text_agent_filter/agent_auth_client0/result.json, tests/snapshots/test_app/test_chat_text_agent/agent_client0/result.json, tests/snapshots/test_app/test_chat_text_filter_agent/agent_auth_client0/result.json
* Fix max subqueries option
* Use reference id order for answer generation
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] …
```
=> Fix UI and answer gen issues

app/frontend/src/pages/ask/Ask.tsx
Fix file upload button behavior in Ask page to properly restrict access based on authentication status. 
**Problem:** The UploadFile component in Ask.tsx was using `disabled={loggedIn}` which incorrectly disabled the button when users were logged in and enabled it when users were not logged in - the opposite of the intended behavior.
**Solution:** Changed the disabled prop to `disabled={!loggedIn}` to match the same authentication logic used in `Chat.tsx`, ensuring that:
- File upload functionality is disabled when no user is logged in
- File upload functionality is enabled when a user is authenticated
- Consistent behavior across both Ask and Chat pages
**Impact:** This ensures proper access control for file upload features and maintains consistent user experience throughout the …
=> Fix: UploadFile button incorrectly disabled when user is logged in

app/backend/approaches/approach.py, app/frontend/package-lock.json, docs/reasoning.md
Adding o3 and o4-mini so that developers may use them without error.
Also upgraded package-lock to reflect package.json minimum node requirement.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local …
```
=> Updates to add latest omni models, upgrade package lock

app/backend/error.py, tests/snapshots/test_app/test_ask_handle_exception/client0/result.json, tests/snapshots/test_app/test_ask_handle_exception/client1/result.json, tests/snapshots/test_app/test_chat_handle_exception/client0/result.json, tests/snapshots/test_app/test_chat_handle_exception/client1/result.json, tests/snapshots/test_app/test_chat_handle_exception_streaming/client0/result.jsonlines, tests/snapshots/test_app/test_chat_handle_exception_streaming/client1/result.jsonlines, tests/snapshots/test_app/test_chat_stream_handle_exception/client0/result.json, tests/snapshots/test_app/test_chat_stream_handle_exception/client1/result.json, tests/test_cosmosdb.py
Fixes #2678
This pull request updates the error message shown when the app encounters an exception. The new message directs you to check the application logs for a full traceback, replacing the previous reference to aka.ms/appservice-logs. This is a better experience since developers may see the message locally, on Container Apps (the new default), or App Service (the old default). In the future, we could add a page that was specific about how to find logs across all three environments, but such a page doesn't exist yet, so better to remove the outdated link for now.
```
[ ] Yes
[X] No
```
This repository is referenced by [this …
=> Update error message to be platform agnostic

.github/workflows/python-test.yaml, .gitignore, CONTRIBUTING.md, requirements-dev.txt
This pull request updates the Python testing workflow to strengthen code coverage requirements and add a diff coverage check. The main changes focus on enforcing higher coverage standards and ensuring new code is adequately tested.
**Testing and coverage improvements:**
* Increased the minimum required code coverage from 89% to 90% and added an XML coverage report output in the `pytest` command.
* Added a new step to check diff coverage using `diff-cover`, comparing against the main branch and enforcing a minimum of 90% coverage for changed code.
```
[ ] Yes
[X] No
```
This repository is referenced by [this …
=> Add test coverage to CI workflow

.devcontainer/devcontainer.json
There are issues with "trixie" ubuntu image right now, so this PR pins the dev container image to bookworm instead:
https://github.com/devcontainers/features/issues?q=is%3Aissue%20state%3Aopen%20docker-in-docker
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[X] …
```
=> Pin devcontainer to bookworm

AGENTS.md, app/backend/requirements.txt, tests/mocks.py, tests/test_auth_init.py
This PR adds tests for the auth_init.py script, with mocks for the network requests to the Graph SDK.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no …
```
=> Add tests for auth_init.py
